
service: olympicsapi

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  events:
    handler: handler.events
    events:
      - http:
        path: /events
        method: get
